spring.application.name=TaskBuddy2

spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/taskbuddy}
spring.datasource.username=${JDBC_DATABASE_USERNAME:postgres}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update    